# See: https://docs.github.com/en/actions/creating-actions
name: Gem Push
author: FreeAgent
description: Push gem packages to a rubygems compatible repository
inputs:
  package-glob:
    description: File glob to match the .gem files to push
    default: "pkg/*.gem"
  release:
    description: Whether to push release versions
    default: true
  pre-release:
    description: Whether to push pre-release versions
    default: true
  tag-release:
    description: After pushing a new gem version, git tag with the version string
    default: true
  key-name:
    description: "Name of credentials key to use from ~/.gem/credentials. Use github for gh packages."
    default: ""
outputs:
  pushed-version:
    description: "The version of the gem pushed to the repository"
    value: ${{ steps.push-gem.outputs.pushed-version }}

runs:
  using: "composite"
  steps:
    - name: Push Gem
      id: push-gem
      shell: bash
      env:
        # Expects GEM_HOST and GEM_HOST_API_KEY to be set
        INPUT_PACKAGE_GLOB: ${{ inputs.package-glob }}
        INPUT_RELEASE:      ${{ inputs.release }}
        INPUT_PRE_RELEASE:  ${{ inputs.pre-release }}
        INPUT_TAG_RELEASE:  ${{ inputs.tag-release }}
        INPUT_KEY_NAME:     ${{ inputs.key-name }}
      run: |
        PATH="${{ github.action_path }}:$PATH"
        gem-push-action
