# See: https://docs.github.com/en/actions/creating-actions
name: Gem Push
author: FreeAgent
description: Push gem packages to a rubygems compatible repository
inputs:
  key:
    description: "Name of credentials key to use from ~/.gem/credentials. Use github for gh packages."
    default: ""
  package-glob:
    description: File glob to match the .gem files to push
    default: "pkg/*.gem"
  pre-release:
    description: Whether to push pre-release versions, instead of release versions (the default).
    default: false
  tag-release:
    description: After pushing a new gem version, git tag with the version string
    default: true
outputs:
  pushed-version:
    description: "The version of the gem pushed to the repository"
    value: ${{ steps.push-gem.outputs.pushed-version }}

runs:
  using: "composite"
  steps:
    - name: Push Gem
      id: push-gem
      shell: bash
      env:
        # Expects GEM_HOST and GEM_HOST_API_KEY to be set
        INPUT_PRE_RELEASE:  ${{ inputs.pre-release }}
        INPUT_TAG_RELEASE:  ${{ inputs.tag-release }}
        INPUT_KEY:          ${{ inputs.key }}
      run: |
        PATH="${{ github.action_path }}:$PATH"
        gem-push-action ${{ inputs.package-glob }}
